export enum FiscalDocumentStatusEnum {
  NAO_EMITIDO = 'NAO_EMITIDO',
  PENDENTE = 'PENDENTE',
  PROCESSANDO = 'PROCESSANDO',
  AUTORIZADO = 'AUTORIZADO',
  REJEITADO = 'REJEITADO',
  ERRO = 'ERRO',
  CONTINGENCIA = 'CONTINGENCIA',
  CANCELAMENTO_PENDENTE = 'CANCELAMENTO_PENDENTE',
  CANCELADO = 'CANCELADO',
  INUTILIZADO = 'INUTILIZADO',
}
